micronaut:
  application:
    name: recruitment-platform
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
    - pattern: /swagger/**
      access: isAnonymous()
    - pattern: /swagger-ui/**
      access: isAnonymous()
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
