package krystian.kryszczak.recruitment.service.security.credentials.being.candidate

import krystian.kryszczak.recruitment.model.security.credentials.being.candidate.CandidateCredentials
import krystian.kryszczak.recruitment.service.security.credentials.being.BeingCredentialsService

interface CandidateCredentialsService : BeingCredentialsService<CandidateCredentials>
